### ISSUE TITLE
Practica8 MelyNoe

### ISSUE THREAD

**Issue by mel-16** [SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-los-3-mosqueteros-topicos#2]
[Practica 8.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visualizacion-de-datos-los-3-mosqueteros-topicos/files/8959889/Practica.8.pdf)

**Comment by Litzy-lopez4** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
